issuer: http://127.0.0.1:5556/dex

storage:
  type: memory

web:
  http: 0.0.0.0:5556
  allowedOrigins:
  - '*'

logger:
  level: "debug"
staticClients:
- id: example
  redirectURIs:
  - 'http://127.0.0.1:5555/callback'
  name: 'example'
  secret: ''
  public: true
connectors:
- type: mockCallback
  id: mock
  name: Example

enablePasswordDB: true

staticPasswords:
- email: "user@test.com"
  hash: "$2a$12$drTCU7tD859aVXpVIztdLOjinb15Xdw.dle4f3QZ1xXninl2r7MRG"
  username: "user@test.com"
  userID: "1234567890"
  companies:
    - name: "Test"
      plan: "Plan 1"
    - name: "Tst"
      plan: "Plan 2"
